### ISSUE TITLE
grbl 1.1

### ISSUE THREAD

**Issue by MoonshineSG** [CarlosGS/Cyclone-PCB-Factory#63]
any plans to update to the new version of [grbl](https://github.com/gnea/grbl/) for RAMPS/Cyclone ?

**Comment by CarlosGS** [comment]
At the moment I'm quite happy with this version, it has worked very well so
far.

So sorry but I don't plan on updating it any longer.

On 28 Dec 2016 03:31, "ǝuıɥsuooɯ" <notifications@github.com> wrote:

any plans to update to the new version of grbl
<https://github.com/gnea/grbl/> for RAMPS/Cyclone ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CarlosGS/Cyclone-PCB-Factory/issues/63>, or mute the
thread

**Comment by MoonshineSG** [comment]
Yes, it does work quite well. Some unsupported commands, but nothing that can't be worked around.
I was just wondering on the longer term plans. Second sentence answers that.thanks.

Great work, btw.

**Comment by MoonshineSG** [comment]
oh... one of the main reasons why 1.1 is interesting is the laser support... just saying...

**Comment by CarlosGS** [comment]
Maybe if I build a laser cutter in the future! I'm still waiting for high power laser diodes to drop in price a little bit.

**Comment by CarlosGS** [comment]
I've moved this issue to the GRBLforCyclone repo: https://github.com/CarlosGS/grblForCyclone/issues/1
